name: PR sanity check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean -B package  --file pom.xml -DskipTests

      - name: Lint
        run: mvn spotless:check

      - name: Tests
        run: mvn clean install

      - name: Get project version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::$VERSION"

      - name: Trivy Security Scan
        run: |
          mvn tech.orla:trivy-maven-plugin:${{ steps.get_version.outputs.version }}:trivy-scan